source 'http://rubygems.org'

gem 'activerecord', :require => 'active_record'
gem 'sinatra-activerecord', :require => 'sinatra/activerecord'
gem 'faker'
gem 'sinatra'
gem 'sqlite3'
gem 'pry'
gem 'rake'
gem 'require_all'
gem 'shotgun'
